name: boranemobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  http: ^1.2.1
  maplibre_gl: any
  flutter_map: ^8.2.2
  latlong2: ^0.9.0
  geolocator: ^12.0.0
  provider: ^6.1.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_bora_ne.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true